# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /#top
    weight: 10
  - name: Meetings
    weight: 20
    hasChildren: true
  - parent: Meetings
    name: Past
    url: past/
  - parent: Meetings
    name: Upcoming
    url: upcoming/
  - name: Events
    url: /#events
    weight: 30

